---
hosts::host_entries:
 'redisnode1.max.com':
   ip: '192.168.56.101'
   host_aliases:
     - 'redisnode1'
 'redisnode2.max.com':
   ip: '192.168.56.102'
   host_aliases:
     - 'redisnode2'
 'redisnode3.max.com':
   ip: '192.168.56.103'
   host_aliases:
     - 'redisnode3'
 'redisnode4.max.com':
   ip: '192.168.56.104'
   host_aliases:
     - 'redisnode4'
