#cloud-config

coreos:
  update:
    reboot-strategy: "off"

  etcd2:
    name: {{ETCD_NODE_NAME}}
    initial-cluster: {{ETCD_INITIAL_CLUSTER}}
    advertise-client-urls: http://$private_ipv4:2379
    listen-client-urls: http://0.0.0.0:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-peer-urls: http://$private_ipv4:2380

  units:
    - name: docker.service
      drop-ins:
        - name: 20-http-proxy.conf
          content: |
            [Service]
            Environment="HTTP_PROXY=http://172.17.0.1:3128"
        - name: 50-insecure-registry.conf
          content: |
            [Service]
             Environment='DOCKER_OPTS=--registry-mirror="https://proxy.tdocker.com:5000" --insecure-registry="proxy.tdocker.com:5000"'
      command: restart
    - name: format-var-lib-docker.service
      command: start
      content: |
        [Unit]
        Before=docker.service var-lib-docker.mount
        ConditionPathExists=!/var/lib/cache/docker.btrfs
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/truncate --size=5G /var/lib/cache/docker.btrfs
        ExecStart=/usr/sbin/mkfs.btrfs /var/lib/cache/docker.btrfs
    - name: var-lib-docker.mount
      enable: true
      content: |
        [Unit]
        Before=docker.service
        After=format-var-lib-docker.service
        Requires=format-var-lib-docker.service
        [Install]
        RequiredBy=docker.service
        [Mount]
        What=/var/lib/cache/docker.btrfs
        Where=/var/lib/docker
        Type=btrfs
        Options=loop,discard  
    - name: etcd2.service
      command: start

