#!/bin/bash
#
# Create individual SQL files for each database. These files
# are imported automatically during an initial provision if
# the databases exist per the import-sql.sh process.

MYSQL_USER="root"
MYSQL_PASSWORD="mmmm"

mysql mysql --user=$MYSQL_USER  --password=$MYSQL_PASSWORD -e 'show databases' | \
grep -v -F "information_schema" | \
grep -v -F "performance_schema" | \
grep -v -F "mysql" | \
grep -v -F "test" | \
grep -v -F "Database" | \
while read dbname; do mysqldump --user=$MYSQL_USER  --password=$MYSQL_PASSWORD "$dbname" > /srv/database/backups/"$dbname".sql && echo "Database $dbname backed up..."; done
