# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$mirrors_yum = <<SCRIPT
yum install curl -y
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
curl http://mirrors.163.com/.help/CentOS6-Base-163.repo -o /etc/yum.repos.d/CentOS-Base.repo
yum clean all && yum makecache
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

   #config.vm.box = "puppetlabs/centos-6.6-64-puppet"
  config.vm.box = "centos/7"
  #config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"
   config.ssh.insert_key = false
  
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope       = :box # or :machine
    config.cache.auto_detect = false
  end

   config.vm.provision :hosts do |provisioner|
      provisioner.autoconfigure = true
      provisioner.sync_hosts = true
      provisioner.add_localhost_hostnames = false
   end
  
  config.vm.define :one do |one| 
    one.vm.hostname = "master.ambari"
    one.vm.network :private_network, ip: "192.168.56.101"
    one.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end     
  end

  config.vm.define :two do |two| 
    two.vm.hostname = "agent1.ambari"
    two.vm.network :private_network, ip: "192.168.56.102"
    two.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end    
  end

  config.vm.define :three do |three| 
    three.vm.hostname = "agent2.ambari"
    three.vm.network :private_network, ip: "192.168.56.103"
    three.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end   
  end
  
  config.vm.synced_folder "puppet", "/etc/puppetlabs/puppet"
  config.vm.provision :shell, path: "shell/base.sh"
  config.vm.provision :puppet do |puppet|
        puppet.environment_path = ["vm", "/etc/puppetlabs/puppet/environments"]
        puppet.environment = "production"
        #puppet.facter = {
        #      "use_debug" => "true"
        #}
        puppet.options = "--verbose --debug "       
  end

end
