VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  config.vm.define "mysql" do |mysql|
	mysql.vm.provider "docker" do |d|
      d.image = "mysql"
      d.name = "mysql"
      d.ports=["3306:3306"]
      d.env={"MYSQL_ROOT_PASSWORD"=>"mmmm"}
    end
  end
  
  config.vm.define "redis" do |redis|
	redis.vm.provider "docker" do |d|
      d.image = "redis"
      d.name = "redis"
      d.ports=["6379:6379"]
    end
  end
  
  config.vm.define "postgresql" do |postgresql|
	postgresql.vm.provider "docker" do |d|
      d.name = "postgresql"
      d.build_dir= "./docker/postgres"   
      d.has_ssh= true
      d.ports=["5432:5432"]
    end
  end
  
  config.vm.define "web" do |web|
    web.vm.box = "max/ubuntu14"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.33"
    web.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
  end
  
end
