forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-ntp'    
mod 'ghoneycutt-hosts'
mod 'puppetlabs-firewall'
mod  'puppetlabs-postgresql'
mod 'puppet-cloudera',
  :git => "git@github.com:puppetmax/puppet-cloudera.git"

mod 'puppet-ssh',
  :git => "https://github.com/saz/puppet-ssh.git"


