forge "https://forge.puppetlabs.com"

mod 'puppetlabs-ntp'    
mod 'ghoneycutt-hosts'
mod 'thias-tuned'
mod 'alexharvey-disable_transparent_hugepage'
mod 'unibet-ambari'
mod 'cesnet-zookeeper',
  :git => "https://github.com/MetaCenterCloudPuppet/cesnet-zookeeper.git"

