# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$mirrors_apt = <<SCRIPT
apt-get install curl -y
mv /etc/apt/sources.list /etc/apt/sources.list.backup
curl http://mirrors.163.com/.help/sources.list.trusty -o /etc/apt/sources.list
apt-get update
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "centos/6"
  #config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"
  config.ssh.insert_key = false
  config.vm.box_check_update = false
 
  #if Vagrant.has_plugin?("vagrant-proxyconf")
  #  config.proxy.http     = "http://172.17.0.6:3142/"
  #  config.proxy.https    = false
  #  config.proxy.no_proxy = "localhost,127.0.0.1"
  #end
  
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  
  config.vm.define :one do |one| 
    one.vm.hostname = "one.cluster"
    one.vm.network :private_network, ip: "192.168.56.121"
    one.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2046]
    end   
  end

  config.vm.define :two do |two| 
    two.vm.hostname = "two.cluster"
    two.vm.network :private_network, ip: "192.168.56.122"
    two.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 4096]
    end   
  end

  config.vm.define :three do |three| 
    three.vm.hostname = "three.cluster"
    three.vm.network :private_network, ip: "192.168.56.123"
    three.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 4096]
    end   
  end
  
  
   config.vm.provision :hosts do |provisioner|
      provisioner.autoconfigure = true
      provisioner.sync_hosts = true
      provisioner.add_localhost_hostnames = false
   end
   
  config.vm.synced_folder "puppet", "/etc/puppetlabs/code"
  
  #config.vm.provision :shell, :inline => $mirrors_apt
  
  config.vm.provision :shell, path: "shell/base.sh"
  config.vm.provision :puppet do |puppet|
        puppet.environment_path = ["vm", "/etc/puppetlabs/code/environments"]
        puppet.environment = "production"
        #puppet.facter = {
        #      "use_debug" => "true"
        #}
        puppet.options = "--verbose --debug "       
  end

end
