app:
    image: yappabe/data
    volumes:
        - .:/var/www/app
        - /vendor
    tty: true

nginx:
    image: yappabe/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    environment:
        DOCUMENT_ROOT: /var/www/app/web
        INDEX_FILE: app_dev.php
        PHP_FPM_SOCKET: php:9000

mysql:
    image: tutum/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_PASS: dev
        MYSQL_USER: dev
        ON_CREATE_DB: dev

php:
    image: yappabe/php
    ports:
        - 9000:9000
    volumes_from:
        - app
    links:
        - mysql
        - mailcatcher

mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
