forge "https://forge.puppetlabs.com"

mod 'puppetlabs-apt', '2.3.0'
mod 'puppetlabs-ntp'    
mod 'puppetlabs-firewall', '1.8.1'
mod 'puppetlabs-java', '1.6.0'

mod 'tylerwalts-jdk_oracle', '1.5.0'
mod 'cesnet-hadoop', '2.4.3'
    
mod 'cesnet-hadoop_lib', '0.2.1'

mod 'cesnet-hbase', '0.11.0'

mod 'cesnet-zookeeper',
  :git => "https://github.com/MetaCenterCloudPuppet/cesnet-zookeeper.git"

